"""Shared enumerations used across the application."""

from enum import Enum


class DecisionStatus(str, Enum):
    APPROVED = "APPROVED"
    DENIED = "DENIED"
    ESCALATED = "ESCALATED"


class AgentStatus(str, Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    REVOKED = "REVOKED"


class ActorType(str, Enum):
    AGENT = "AGENT"
    HUMAN = "HUMAN"
    ORGANIZATION = "ORGANIZATION"


class PolicyType(str, Enum):
    SPEND_LIMIT = "SPEND_LIMIT"
    ALLOWLIST = "ALLOWLIST"
    BLOCKLIST = "BLOCKLIST"
    APPROVAL_THRESHOLD = "APPROVAL_THRESHOLD"
    TIME_WINDOW = "TIME_WINDOW"


class TransactionStatus(str, Enum):
    SUBMITTED = "SUBMITTED"
    EVALUATED = "EVALUATED"
    APPROVED = "APPROVED"
    DENIED = "DENIED"
    ESCALATED = "ESCALATED"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"


class ApprovalAction(str, Enum):
    APPROVE = "APPROVE"
    DENY = "DENY"


class ProofStatus(str, Enum):
    GENERATED = "GENERATED"
    ANCHORED = "ANCHORED"
    FAILED = "FAILED"


class AuditEventType(str, Enum):
    AGENT_CREATED = "AGENT_CREATED"
    AGENT_UPDATED = "AGENT_UPDATED"
    POLICY_CREATED = "POLICY_CREATED"
    POLICY_UPDATED = "POLICY_UPDATED"
    TRANSACTION_SUBMITTED = "TRANSACTION_SUBMITTED"
    TRANSACTION_EVALUATED = "TRANSACTION_EVALUATED"
    TRANSACTION_APPROVED = "TRANSACTION_APPROVED"
    TRANSACTION_DENIED = "TRANSACTION_DENIED"
    TRANSACTION_ESCALATED = "TRANSACTION_ESCALATED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_COMPLETED = "APPROVAL_COMPLETED"
    PROOF_GENERATED = "PROOF_GENERATED"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
